
#INITIAL SETTINGS
data_dir: "./Data/"
weights_dir: "./Weights"
train_csv: "fashion-mnist_train.csv"
test_csv: "fashion-mnist_test.csv"
model_name: trained_weights.h5

#PARAMETERS
IMG_ROWS: 28
IMG_COLS: 28
NUM_CLASSES: 10
TEST_SIZE: 0.2

#TRAINING
NUM_EPOCHS: 10
BATCH_SIZE: 128


